BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS Users (
    username VARCHAR(32) PRIMARY KEY,
    password VARCHAR(64),
    lastLogin DATETIME DEFAULT CURRENT_TIMESTAMP,
    azureId VARCHAR(32)
);

COMMIT;