BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS Users (
    userID IDENTITY(1,1) PRIMARY KEY,
    username VARCHAR(32),
    password VARCHAR(64),
    lastLogin DATETIME DEFAULT CURRENT_TIMESTAMP,
    azureId VARCHAR(32)
);

COMMIT;